### ISSUE TITLE
Kambrik seems to corrupt the output of the console. [Fabric 1.19.2]

### ISSUE THREAD

**Issue by LittleCircleOO** [ejektaflex/Kambrik#19]
After I added Kambrik, my console output went from
![Normal](https://user-images.githubusercontent.com/51949761/231182608-96a7a017-3927-4304-be5d-3db1071ccc3e.png)
to
![Exception](https://user-images.githubusercontent.com/51949761/231182632-fc9ea444-238c-40df-8bd2-407ace317638.png)
Another more obvious example is that it prevents the [Better Fabric Console](https://modrinth.com/mod/better-fabric-console) from working properly on Fabric 1.19.2.
I'm confused because these problems are not reproduced on the latest 1.19.4. Since many of the mods currently remain in 1.19.2, I was hoping for a fix for 1.19.2.

**Comment by ejektaflex** [comment]
This shouldn't be Kambrik - I haven't the foggiest idea what it *could* be, but Kambrik doesn't really touch the console, besides a logger reconfiguration (which might reset loggers of other mods and has since been fixed), but these don't look like messages sent with a logger. Kambrik doesn't even have language localizations, nor does it have any mixins for any game related code.

I'd suggest that you try experiment by removing and then readding half of your other mods besides Kambrik over and over until you can find out if another mod combined with Kambrik causes this to happen (I am guessing that it's either another mod's problem, OR a conflict between Kambrik and another mod). Since I've never seen this before, I assume that it's some sort of conflict.

Once you've narrowed down which other mod is causing this, we can figure out whether the problem rests on Kambrik's end or their end!

**Comment by LittleCircleOO** [comment]
I'm sorry for the confusion caused by the previous bug description. The garbled code in the console may be due to text encoding. Here is the output after replacing the device.
![Issue](https://user-images.githubusercontent.com/51949761/231321162-8e6168d5-d8ae-45d4-b6a5-8a6e47e63412.png)
Only **Luckperms (5.4.55, for testing color output), [better-fabric-console](https://github.com/jpenilla/better-fabric-console/releases/tag/v1.1.2) (1.1.2, for implementing console color output), [fabric-api](https://modrinth.com/mod/fabric-api/version/0.76.0+1.19.2), [fabric-language-kotlin](https://modrinth.com/mod/fabric-language-kotlin/version/1.9.3+kotlin.1.8.20), and [Kambrik](https://www.curseforge.com/minecraft/mc-mods/kambrik/files/3937716) (4.0)** are installed on the server side.
 
The problem is that the console **loses all color output and instead outputs the minecraft formatting code directly**, and when Kambrik is removed the console output is normal instead. This problem is not related to Luckperms, as the same problem occurs when I replace Luckperms with other mods that have colored text output.
 
In version 1.19.4, the better fabric console (1.1.4) worked fine when installed together with Kambrik (6.0.0-beta2), but there were no significant code changes to the better fabric console between the two versions.

**Comment by LittleCircleOO** [comment]
Another detail is that in version 1.19.4 the problem still recurs if version 5.1.0 is installed, but after replacing it with version 6.0.0-beta.2 the problem is solved, so I guess the problem is generated by the old version of Kambrik.

**Comment by ejektaflex** [comment]
Well, there you go, it was the logger reconfiguration that I mentioned in my earlier comment, which was fixed in beta.2! 

The old issue is here:
https://github.com/ejektaflex/Kambrik/issues/17

Since it seems to be fixed now and you were only using an old version of Kambrik, I'm going to mark this as closed!
